=== KoJIoc/Lab2.2/Lab2.2/BlogJSONSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "blog",
  "type": "object",
  "properties": {
    "Articles": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Description": {
            "type": "string"
          },
          "Comments": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "TextOfComment": {
                  "type": "string"
                },
                "AnswerComments": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "TextOfComment": {
                        "type": "string"
                      },
                      "AnswerCommentator": {
                        "type": "object",
                        "properties": {
                          "Firstname": {
                            "type": "string"
                          },
                          "Lastname": {
                            "type": "string"
                          },
                          "Id": {
                            "type": "number"
                          }
                        },
                        "required": [
                          "Firstname",
                          "Lastname",
                          "Id"
                        ]
                      },
                      "Id": {
                        "type": "number"
                      }
                    },
                    "required": [
                      "TextOfComment",
                      "AnswerCommentator",
                      "Id"
                    ]
                  }
                },
                "Commentator": {
                  "type": "object",
                  "properties": {
                    "Firstname": {
                      "type": "string"
                    },
                    "Lastname": {
                      "type": "string"
                    },
                    "Id": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "Firstname",
                    "Lastname",
                    "Id"
                  ]
                },
                "Id": {
                  "type": "number"
                }
              },
              "required": [
                "TextOfComment",
                "AnswerComments",
                "Commentator",
                "Id"
              ]
            }
          },
          "Tags": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "Title": {
                  "type": "string"
                },
                "Description": {
                  "type": "string"
                },
                "Id": {
                  "type": "number"
                }
              },
              "required": [
                "Title",
                "Description",
                "Id"
              ]
            }
          },
          "DateOfCreation": {
            "type": "string"
          },
          "Id": {
            "type": "number"
          }
        },
        "required": [
          "Description",
          "Comments",
          "Tags",
          "DateOfCreation",
          "Id"
        ]
      }
    },
    "Title": {
      "type": "string"
    },
    "Owner": {
      "type": "object",
      "properties": {
        "Firstname": {
          "type": "string"
        },
        "Lastname": {
          "type": "string"
        },
        "Id": {
          "type": "number"
        }
      },
      "required": [
        "Firstname",
        "Lastname",
        "Id"
      ]
    },
    "Description": {
      "type": "string"
    },
    "Id": {
      "type": "number"
    }
  },
  "required": [
    "Articles",
    "Title",
    "Owner",
    "Description",
    "Id"
  ]
}

=== KoJIoc/Lab2.2/Lab2.2/BlogJSON.json
{
  "Articles": [
    {
      "Description": "DescriptionOfArticle",
      "Comments": [
        {
          "TextOfComment": "TextOfComment",
          "AnswerComments": [
            {
              "TextOfComment": "TextOfAnswerComment",
              "AnswerCommentator": {
                "Firstname": "Firstname",
                "Lastname": "Lastname",
                "Id": 1
              },
              "Id": 1
            }
          ],
          "Commentator": {
            "Firstname": "Firstname",
            "Lastname": "Lastname",
            "Id": 1
          },
          "Id": 1
        }
      ],
      "Tags": [
        {
          "Title": "TitleOfTag",
          "Description": "DescriptionOfTag",
          "Id": 1
        }
      ],
      "DateOfCreation": "2023-05-17T00:00:00",
      "Id": 1
    }
  ],
  "Description": "DescriptionOfBlog",
  "Id": 1,
  "Owner": {
    "Firstname": "Firstname",
    "Lastname": "Lastname",
    "Id": 1
  },
  "Title": "TitleOfBlog"
}

=== KoJIoc/Lab2.2/Lab2.2/BlogJSONRead.json
{"Articles":[{"Description":"DescriptionOfArticle","Comments":[{"TextOfComment":"TextOfComment","AnswerComments":[{"TextOfComment":"TextOfAnswerComment","AnswerCommentator":{"Firstname":"Firstname","Lastname":"Lastname","Id":1},"Id":1}],"Commentator":{"Firstname":"Firstname","Lastname":"Lastname","Id":1},"Id":1}],"Tags":[{"Title":"TitleOfTag","Description":"DescriptionOfTag","Id":1}],"DateOfCreation":"2023-05-17T00:00:00","Id":1}],"Title":"TitleOfBlog","Owner":{"Firstname":"Firstname","Lastname":"Lastname","Id":1},"Description":"DescriptionOfBlog","Id":1}
